commit homework_1
odessabear/o_mykhailov pull request #1
Opened 2022-06-22 22:33 UTC by odessabear

2022-07-05 16:06 UTC, KostyantynPanchenko requested changes
Потребує доопрацювання:

- коректно налаштувати gitignore
- відформатувати весь код відповідно до Java code style (щоб пробіли були там де мають бути і не було там де їм не потрібно бути, наявність та відсутність порожніх стрічок там де потрібно)

2022-07-05 18:42 UTC, odessabear commented
Вітаю!
Начебто виправив, якщо, щось упустив, буду дуже вдячний за підказку.
З повагою.

2022-07-07 10:48 UTC, odessabear commented
Вітаю.Видалив зайве з комміту, то був таки факап, але і наука.
З приводу .gitignore,  зробив один файл на рівні репозиторію, та другий на рівні модуля з домашкою, не знаю, чи це вірне рішення.) Налаштування брав з гугла для репозиторію, для модуля з автогенерації Spring Boot. Я не зустрічав канонічного налаштування для ігнору, шукав і раніше. Якщо підкажете, де подивитись, буду дуже вдячний.

2022-07-08 06:12 UTC, KostyantynPanchenko approved these changes

2022-07-08 06:46 UTC, merged